import { QueryClientProvider } from '@/shared/apis/queryClientProvider';
import type { Metadata, Viewport } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="mx-auto h-dvh max-w-[375px] bg-black">
        <QueryClientProvider>{children}</QueryClientProvider>
      </body>
    </html>
  );
}
